### ISSUE TITLE
Framebuffer drivers are missing?

### ISSUE THREAD

**Issue by xenoxaos** [apc-io/apc-8750#1]
Trying to compile the FB drivers fails.

**Comment by projectgus** [comment]
Hi xenoxaos,

I noticed that you closed this and deleted your comment from the other issue I raised. Was there an update on source available for these?

Cheers,

Angus

**Comment by xenoxaos** [comment]
I'm in contact directly with VIA regarding this issue.  Seeing as how you are the only one watching my fork, you will be one of the first to know anything that comes of it!

**Comment by projectgus** [comment]
That's great to hear.

I hope they get the message on this, the WM8710 is a great chipset at the price (not just the apc.io, lots of sub-$60 media devices.) If VIA/WM come to the party with community support, people will make some really great things.

(That said, I've been banging on about this for a while now. http://projectgus.com/2010/11/open-letter-to-wondermedia-technologies/ )

**Comment by mpthompson** [comment]
Any movement on the frame buffer drivers?  I have a port of Raspbian (36,000 Debian Wheezy armhf packages backported to support the armv6+fpu) that runs great on the APC, but it's frustrating that it can only be used in a headless configuration because the frame buffer drivers are missing.  Ugh!!!
